const globalWeatherState = {
  city: {
    name: "Dreamcity",
    country: "Dreamland",
  },
  currTime: undefined,
  timezone: undefined,
  weather: {
    main: undefined,
    temp: undefined,
    celsiusTemp: undefined,
    fahrenheitTemp: undefined,
    wind: undefined,
    humidity: undefined,
    pressure: undefined,
    cloudiness: undefined,
    uvIndex: undefined,
  },
  airQuality: {
    overall: undefined,
    components: {
      co: undefined,
      so2: undefined,
      no2: undefined,
      o3: undefined,
      pm2_5: undefined,
    },
  },
  sun: {
    sunrise: undefined,
    sunset: undefined,
  },
  hourlyForecast: {
    plus1: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus2: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus3: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus4: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus5: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus6: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus7: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus8: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus9: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus10: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus11: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus12: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus13: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus14: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus15: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus16: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus17: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus18: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus19: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus20: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus31: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus22: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus23: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus24: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
  },
  dailyForecast: {
    plus1: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus2: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus3: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus4: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus5: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus6: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus7: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
    plus8: {
      main: undefined,
      temp: undefined,
      celsiusTemp: undefined,
      fahrenheitTemp: undefined,
      date: undefined,
    },
  },
};

export default globalWeatherState;
